env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
      FunctionDeclaration:
        parameters: 2
      FunctionExpression:
        parameters: 2
      CallExpression:
        arguments: 2
  linebreak-style:
    - error
    - unix
  no-console: "off"
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - always
  no-constant-condition:
    - error
    - checkLoops: false
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
